### ISSUE TITLE
Unable to download anything from Crunchyroll anonymously or with cookies.txt

### ISSUE THREAD

**Issue by ghost** [r33int/crunchyrollDownloader#5]
Using elementary OS with the most recent version of youtube-dl.

```
[Crunchyroll] 727589: Downloading webpage

Traceback (most recent call last):
  
File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)

  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals

  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>

  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 471, in main

  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 461, in _real_main

  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1989, in download

  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 785, in extract_info

  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 440, in extract

  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/crunchyroll.py", line 421, in _real_extract

  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/crunchyroll.py", line 126, in _download_webpage

  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 634, in _download_webpage

  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 539, in_download_webpage_handle

  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 519, in _request_webpage
  
File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2199, in urlopen

  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)

  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)

  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)

  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 945, in http_open

  File "/usr/lib/python2.7/urllib2.py", line 1195, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)

  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)

  File "/usr/lib/python2.7/httplib.py", line 1096, in _send_request
    self.putheader(hdr, value)

  File "/usr/lib/python2.7/httplib.py", line 1035, in putheader
    raise ValueError('Invalid header value %r' % (one_value,))

ValueError: Invalid header value 'EC24_CR_TO_VRV=7fc56270e7a70fa81a5935b72eacbe29_1\r; ajs_user_id=%2275880549%22\r; ajs_anonymous_id=%2216e8fba3-1935-431e-88b1-14d32319e930%22\r; cf_clearance=6b58df72d1b6cd99a0f6ff8dcd9b6f1c0ca1dc49-1523156085-604800\r; c_userkey=2%3AuOGcNf1UAS8kMCkZ1T4CL%2B7SR5s%3D\r; c_userid=75880549\r; ajs_group_id=null\r; c_visitor=358fd044-fcb7-40fb-b7d0-c8fdc0767488\r; __cfduid=dbbb5116322fe3339856ac0b64c9ef85f1523156040\r; c_d=p%3D0\r; blockTrack=1\r'
```

**Comment by r33int** [comment]
How did you install youtube-dl?

**Comment by ghost** [comment]
Once through the Ubuntu repositories, and a second time through the developer's websites using the script provided.

**Comment by r33int** [comment]
I really don't know then, sorry. I suggest you opening an issue at youtube-dl: https://github.com/rg3/youtube-dl

The script itself seems to be running fine.
